# Generated by Django 5.1.5 on 2025-02-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0002_remove_img_product_img_name_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Img',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
