# Generated by Django 5.1.5 on 2025-02-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0014_customers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
